#!/usr/bin/env python3
"""Reconcile two independent Step16-v8 blind reviews without leaking decisions."""

from __future__ import annotations

import argparse
import json
from collections import Counter
from pathlib import Path

import step15_v8_common as common


ROOT = Path(__file__).resolve().parent.parent

REVIEW_FIELDS = [
    "review_candidate_uid",
    "seller_uid_left",
    "seller_uid_right",
    "shared_identifier_types",
    "shared_identifier_values",
    "left_context_preview",
    "right_context_preview",
    "reviewer_id",
    "identity_label",
    "evidence_type",
    "confidence",
    "notes",
]

IMMUTABLE_FIELDS = REVIEW_FIELDS[:7]
ALLOWED_DECISIONS = {
    ("positive", "same_controller_direct_identifier"),
    ("positive", "same_controller_component_anchor"),
    ("negative", "public_contact_or_url_noise"),
    ("negative", "template_clone_not_controller"),
    ("negative", "semantic_topic_not_controller"),
    ("negative", "ordinary_negative"),
    ("uncertain", "uncertain_insufficient_evidence"),
}


def relative(path: Path) -> str:
    return str(path.resolve().relative_to(ROOT)).replace("\\", "/")


def validate_summary(path: Path) -> dict:
    summary = common.load_json(path)
    expected = summary.get("summary_sha256")
    unsigned = dict(summary)
    unsigned.pop("summary_sha256", None)
    if expected != common.canonical_hash(unsigned):
        raise ValueError(f"Queue summary self-hash is invalid: {path}")
    producer = ROOT / "scripts" / "step16_build_v8_context_review_queues.py"
    if summary.get("producer_sha256") != common.sha256(producer):
        raise ValueError("Queue summary was generated by a different queue-builder revision")
    return summary


def load_template(summary: dict, role: str) -> tuple[Path, list[dict]]:
    record = summary["blind_review_templates"][role]
    path = common.resolve(record["path"])
    if common.sha256(path) != record["sha256"]:
        raise ValueError(f"Blind template hash changed: {path}")
    rows = common.load_csv(path)
    if rows and list(rows[0]) != REVIEW_FIELDS:
        raise ValueError(f"Unexpected blind template schema: {path}")
    if len({row["review_candidate_uid"] for row in rows}) != len(rows):
        raise ValueError(f"Blind template contains duplicate candidates: {path}")
    return path, rows


def load_completed_superset(path: Path, role: str) -> dict[str, dict]:
    rows = common.load_csv(path)
    if not rows:
        raise ValueError(f"Reviewer {role} file is empty: {path}")
    if list(rows[0]) != REVIEW_FIELDS:
        raise ValueError(f"Unexpected reviewer {role} schema: {path}")
    index = {}
    reviewer_ids = set()
    for row in rows:
        uid = row["review_candidate_uid"].strip()
        if not uid or uid in index:
            raise ValueError(f"Missing or duplicate candidate in reviewer {role} file: {uid}")
        reviewer_id = row["reviewer_id"].strip()
        identity = row["identity_label"].strip().lower()
        evidence = row["evidence_type"].strip()
        confidence = row["confidence"].strip().lower()
        if not reviewer_id:
            raise ValueError(f"Reviewer {role} id is missing for {uid}")
        if (identity, evidence) not in ALLOWED_DECISIONS:
            raise ValueError(f"Invalid reviewer {role} decision for {uid}: {identity}/{evidence}")
        if confidence not in {"high", "medium", "low"}:
            raise ValueError(f"Invalid reviewer {role} confidence for {uid}: {confidence}")
        if not row["notes"].strip():
            raise ValueError(f"Reviewer {role} notes are missing for {uid}")
        reviewer_ids.add(reviewer_id.casefold())
        index[uid] = row
    if len(reviewer_ids) != 1:
        raise ValueError(f"Reviewer {role} file uses multiple reviewer ids: {sorted(reviewer_ids)}")
    return index


def materialize_subset(template_rows: list[dict], reviewed: dict[str, dict], role: str) -> list[dict]:
    output = []
    for template in template_rows:
        uid = template["review_candidate_uid"]
        if uid not in reviewed:
            raise ValueError(f"Reviewer {role} is missing formal candidate {uid}")
        row = reviewed[uid]
        for field in IMMUTABLE_FIELDS:
            if row[field] != template[field]:
                raise ValueError(f"Reviewer {role} changed immutable field {field} for {uid}")
        output.append(dict(row))
    return output


def decision_key(row: dict) -> tuple[str, str, str]:
    return (
        row["identity_label"].strip().lower(),
        row["evidence_type"].strip(),
        row["confidence"].strip().lower(),
    )


def main() -> None:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--queue-summary", required=True)
    parser.add_argument("--reviewer-a-full", required=True)
    parser.add_argument("--reviewer-b-full", required=True)
    parser.add_argument("--output-directory", default=None)
    args = parser.parse_args()

    summary_path = common.resolve(args.queue_summary)
    summary = validate_summary(summary_path)
    template_a_path, template_a = load_template(summary, "reviewer_a")
    template_b_path, template_b = load_template(summary, "reviewer_b")
    adjudicator_template_path, adjudicator_template = load_template(summary, "reviewer_adjudicator")
    universe_a = {row["review_candidate_uid"] for row in template_a}
    universe_b = {row["review_candidate_uid"] for row in template_b}
    universe_c = {row["review_candidate_uid"] for row in adjudicator_template}
    if universe_a != universe_b or universe_a != universe_c:
        raise ValueError("Reviewer template universes differ")

    reviewer_a_path = common.resolve(args.reviewer_a_full)
    reviewer_b_path = common.resolve(args.reviewer_b_full)
    reviewer_a_full = load_completed_superset(reviewer_a_path, "a")
    reviewer_b_full = load_completed_superset(reviewer_b_path, "b")
    subset_a = materialize_subset(template_a, reviewer_a_full, "a")
    subset_b = materialize_subset(template_b, reviewer_b_full, "b")
    reviewer_ids_a = {row["reviewer_id"].strip().casefold() for row in subset_a}
    reviewer_ids_b = {row["reviewer_id"].strip().casefold() for row in subset_b}
    if reviewer_ids_a & reviewer_ids_b:
        raise ValueError("The two independent reviewer ids must differ")

    by_uid_a = {row["review_candidate_uid"]: row for row in subset_a}
    by_uid_b = {row["review_candidate_uid"]: row for row in subset_b}
    disagreement_uids = {
        uid for uid in universe_a if decision_key(by_uid_a[uid]) != decision_key(by_uid_b[uid])
    }
    adjudication_rows = []
    for template in adjudicator_template:
        if template["review_candidate_uid"] not in disagreement_uids:
            continue
        adjudication_rows.append(dict(template))

    output_dir = common.resolve(args.output_directory) if args.output_directory else summary_path.parent
    if output_dir.resolve() != summary_path.parent.resolve():
        output_dir.mkdir(parents=True, exist_ok=True)
    outputs = {
        "reviewer_a": output_dir / "reviewer_a_blind_packet.completed.csv",
        "reviewer_b": output_dir / "reviewer_b_blind_packet.completed.csv",
        "adjudication_template": output_dir / "reviewer_adjudicator_disagreements.template.csv",
        "summary": output_dir / "dual_review_reconciliation_summary.json",
    }
    existing = [path for path in outputs.values() if path.exists()]
    if existing:
        raise FileExistsError(f"Refusing to overwrite reconciliation output: {existing[0]}")
    outputs["reviewer_a"].write_bytes(common.render_csv(subset_a, REVIEW_FIELDS))
    outputs["reviewer_b"].write_bytes(common.render_csv(subset_b, REVIEW_FIELDS))
    outputs["adjudication_template"].write_bytes(common.render_csv(adjudication_rows, REVIEW_FIELDS))

    matched = [uid for uid in universe_a if uid not in disagreement_uids]
    result = {
        "step": "step16_reconcile_v8_dual_reviews",
        "queue_run_id": summary["run_id"],
        "formal_candidate_count": len(universe_a),
        "matching_decision_count": len(matched),
        "disagreement_count": len(disagreement_uids),
        "matching_decision_counts": dict(
            sorted(Counter("/".join(decision_key(by_uid_a[uid])) for uid in matched).items())
        ),
        "adjudication_candidate_uids": sorted(disagreement_uids),
        "reviewer_decisions_hidden_from_adjudication_packet": True,
        "inputs": {
            relative(summary_path): common.sha256(summary_path),
            relative(template_a_path): common.sha256(template_a_path),
            relative(template_b_path): common.sha256(template_b_path),
            relative(adjudicator_template_path): common.sha256(adjudicator_template_path),
            relative(reviewer_a_path): common.sha256(reviewer_a_path),
            relative(reviewer_b_path): common.sha256(reviewer_b_path),
        },
        "outputs": {
            key: {"path": relative(path), "sha256": common.sha256(path)}
            for key, path in outputs.items()
            if key != "summary"
        },
    }
    result["summary_sha256"] = common.canonical_hash(result)
    outputs["summary"].write_text(
        json.dumps(result, indent=2, ensure_ascii=False) + "\n", encoding="utf-8"
    )
    print(json.dumps(result, indent=2, ensure_ascii=False))


if __name__ == "__main__":
    main()
